### ISSUE TITLE
(🎁) "organize imports" integration

### ISSUE THREAD

**Issue by KotlinIsland** [koxudaxi/ruff-pycharm-plugin#140]
the vscode extension has options/commands for:

- organize imports on save
- fix all on save
- a fix all command

I think that it would be beneficial if this plugin had a separate "organise imports" option like the vscode extensions does.

**Comment by urob** [comment]
Isn't this already possible? For me the following combination of options achieves this:
- `Run ruff when the python file is saved`
- `Use ruff format (Experimental) for version 0.0.289 or later`
- Enabling auto-fixing imports in the projects' `pyproject.toml` file:
    ```toml
    [tool.ruff.lint]
    select = ['I']   # add more rules here as desired
    fixable = ['I']  # add more rules here as desired
```
