### ISSUE TITLE
File specific rule not getting applied

### ISSUE THREAD

**Issue by fenilgmehta** [koxudaxi/ruff-pycharm-plugin#277]
Hi team, thanks for this awesome plugin 🙏

**Describe the bug**
The plugin is not taking into account `[per-file-ignores]`

**To Reproduce**
1. Create a ruff file like below (name it `ruff.toml`
```toml
# Enable this list of rules.
select = [
    "S",  # flake8-bandit
]
ignore = []
target-version = "py311"

# Rules to Ignore for matching files.
[per-file-ignores]
# "test files" (i.e. unit tests)
"test_*.py" = [
    "S101",  # Use of assert detected
    "S311",  # Standard pseudo-random generators are not suitable for cryptographic purposes
    "SLF001",  # Private member accessed: {access}
]
```
2. Create python file and name it `test_ruff_rule_in_pycharm.py`
```python
def test_something() -> None:
    """Ruff will highlight the below assert in PyCharm."""
    assert True
```

**Expected behavior**
The `assert` in `test_ruff_rule_in_pycharm.py` should **NOT** be highlighted like the one shown in `Screenshots` section. CLI works perfectly fine.

**Screenshots**
![Screenshot_20231002_164541](https://github.com/koxudaxi/ruff-pycharm-plugin/assets/42742240/0d7fe304-2346-43ed-a51f-ad98b9f6a60a)

**Environments**
 - IDE: PyCharm 2023.2.1 (Professional Edition)
 - OS: Fedora Linux 35
 - Ruff Version 0.0.290
 - Plugin version 0.0.20
