### ISSUE TITLE
(🎁) Config options for specifying what gets run 'on save'

### ISSUE THREAD

**Issue by KotlinIsland** [koxudaxi/ruff-pycharm-plugin#386]
Currently, when enabled, the plugin will run format and `check --fix` on save, I want `format` to run, but not `check --fix`, or maybe I want `check --fix` but definitely not 'remove unused imports' (the absolute worst thing imaginable!)

# Desired
config options for:
- `format` on save
- `check --fix` on save
- organize imports on save
- remove unused import on save

- related #135, #140

**Comment by urob** [comment]
If you are fine with disabling autofixing imports all together, then adding the following to your `pyproject.toml` will do:
```toml
[tool.ruff.lint]
select = ['I']     # warn about unsorted imports
unfixable = ['I']  # but never fix them
```

The problem with that solution is that it also prevents you from manually triggering the sort via the context actions inside the IDE (c.f., #249 for a proposal that would fix this).
