### ISSUE TITLE
(🎁) Show errors in `pyproject.toml` file

### ISSUE THREAD

**Issue by KotlinIsland** [koxudaxi/ruff-pycharm-plugin#390]
It would actually be highly based if the plugin could run on `pyproject.toml`
```toml
[tool.ruff]
target-version = "py312"
asdf = true
```
```
> ruff check
ruff failed
  Cause: Failed to parse C:\Users\AMONGUS\projects\test-python\pyproject.toml
  Cause: TOML parse error at line 521, column 1
    |
521 | [tool.ruff]
    | ^^^^^^^^^^^
unknown field `asdf`
```

So we could show the error in the toml file:
```toml
[tool.ruff] # ruff failed: unknown field `asdf`
target-version = "py312"
asdf = true
```

- related #294
