### ISSUE TITLE
Missing copyright notice at top of file

### ISSUE THREAD

**Issue by PilarczykM** [koxudaxi/ruff-pycharm-plugin#402]
Currently, there's a discrepancy regarding the presence of copyright information at the top of files, where the tool "ruff" informs users about its absence, but plugin not. Are there plans to improve this?

``` sh
__main__.py:1:1: CPY001 Missing copyright notice at top of file
```

pyproject.toml
``` toml
[tool.ruff.lint]
preview = true
extend-select = ["CPY"]
```

Tools:
PyCharm 2023.3.5 (Community Edition
Ruff 0.0.31
